apiVersion: v1
kind: Secret
metadata:
  name: webexteamsbot
type: Opaque
stringData:
  WEBEX_TEAMS_ACCESS_TOKEN: <WEBEX_TEAMS_ACCESS_TOKEN>
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-computer-vision
type: Opaque
stringData:
  AZURE_CV_KEY: <AZURE_CV_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: ifttt
type: Opaque
stringData:
  IFTTT_KEY: <IFTTT_KEY>
  IFTTT_BASE_WEBHOOK_NAME: <IFTTT_BASE_WEBHOOK_NAME>
